// Code generated by rlpgen. DO NOT EDIT.

//go:build !norlpgen
// +build !norlpgen

package types

import "github.com/ethereum/go-ethereum/rlp"
import "io"

func (obj *rlpReadStorage) EncodeRLP(_w io.Writer) error {
	w := rlp.NewEncoderBuffer(_w)
	_tmp0 := w.List()
	w.WriteBytes(obj.Address[:])
	if obj.Slot == nil {
		w.Write(rlp.EmptyString)
	} else {
		if obj.Slot.Sign() == -1 {
			return rlp.ErrNegativeBigInt
		}
		w.WriteBigInt(obj.Slot)
	}
	if obj.Value == nil {
		w.Write(rlp.EmptyString)
	} else {
		if obj.Value.Sign() == -1 {
			return rlp.ErrNegativeBigInt
		}
		w.WriteBigInt(obj.Value)
	}
	w.ListEnd(_tmp0)
	return w.Flush()
}
